source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:year-:month-:day_:title.html

baseurl: /

rdiscount:
  extensions: []

exclude: []

static:
- css
- js
- _layouts
- _includes
- _plugins
- _config.yml

reports_dir: _posts

