source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:year-:month-:day_:title.html

baseurl: /

index_pages:
  category:
    do_related:     false
    title_prefix:   'Lab: '

category_dir: labs

rdiscount:
  extensions: []

exclude: []


static:
- css
- js
- imgs
- _layouts
- _includes
- _plugins
- _config.yml
- favicon.ico

reports_dir: _posts

