source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:year-:month-:day_:title.html

baseurl: /

index_pages:
  category:
    do_related:     false
    title_prefix:   'Lab: '
  analyst:
    do_related:     false
    pluralize:      false
    title_prefix:   'Analyst: '
  researcher:
    do_related:     false
    pluralize:      false
    title_prefix:   'Researcher: '

category_dir: labs
analyst_dir: analyst
researcher_dir: researcher

rdiscount:
  extensions: []

exclude: []


static:
- css
- js
- imgs
- _layouts
- _includes
- _plugins
- _config.yml
- favicon.ico
- data_grid.html

reports_dir: _posts

