source:      .
destination: ./_site
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:year-:month-:day_:title.html

baseurl: /

index_pages:
  category:
    do_related:     false
    title_prefix:   'Category: '
  analyst:
    do_related:     false
    pluralize:      false
    title_prefix:   'Analyst: '
  researcher:
    do_related:     false
    pluralize:      false
    title_prefix:   'Researcher: '
  pi:
    do_related:     false
    pluralize:      false
    title_prefix:   'PI: '

category_dir: category
analyst_dir: analyst
researcher_dir: researcher
pi_dir: pi

rdiscount:
  extensions: []

exclude: []


static:
- css
- js
- imgs
- _layouts
- _includes
- _plugins
- _config.yml
- favicon.ico
- data_grid.html
- config.ru

reports_dir: _posts

