source:      .
destination: ../bioreports
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:year-:month-:day_:title.html

baseurl: /

index_pages:
  category:
    do_related:     false
    title_prefix:   'Lab: '
  analyst:
    do_related:     false
    pluralize:      false
    title_prefix:   'Analyst: '
  researcher:
    do_related:     false
    pluralize:      false
    title_prefix:   'Researcher: '
  pi:
    do_related:     false
    pluralize:      false
    title_prefix:   'PI: '

matches:
  pi:
    Li_L:
      - lil
      - LIL
      - Li_L
    Molecular_Biology:
      - Molecular_Biology
      - molbio
      - agp
    cbio:
      - cbio
      - bio
      - biocore
    Krumlauf:
      - Krumlauf
      - krumlauf
      - rek
    Sanchez:
      - asa
      - Sanchez
      - sanchez
    Hawley:
      - rsh
      - Hawley
    Piotrowski:
      - pio
      - PIO
      - Piotrowski
      - piotrowski
    Gerton:
      - Gerton
      - jeg
      - JEG
    Trainor:
      - pat
      - PAT
      - Trainor
    Mak:
      - hym
      - Mak
      - MAK
      - mak
    Workman:
      - jlw
      - Workman
    Genomics:
      - cws
    Baumann:
      - peb
      - Baumann
    Shilatifard:
      - ash
      - Shilatifard


category_dir: c
analyst_dir: a
researcher_dir: r
pi_dir: pi

rdiscount:
  extensions: []

exclude: []

