source:      .
destination: ../bioreports
includes:    ./_includes

pygments:    true
markdown:    rdiscount
permalink:   /:year-:month-:day_:title.html

baseurl: /

index_pages:
  category:
    do_related: false
    title_prefix: 'Lab: '

rdiscount:
  extensions: []

exclude: []

